### ISSUE TITLE
"Socket connection died" error

### ISSUE THREAD

**Issue by utdream** [iwalton3/python-mpv-jsonipc#14]
Hello,

I've implemented your library and I'm getting the following error:

```
Socket connection died.
Traceback (most recent call last):
  File "/opt/app/env/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 184, in run
    self.callback(json_data)
  File "/opt/app/env/lib/python3.11/site-packages/python_mpv_jsonipc.py", line 310, in event_callback
    self.cid_wait[data["request_id"]].set()
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 7
``` 

The odd thing is that MPV continues running just fine and I can test the socket with no issues. I think the socket is fine but the exception is causing the lib to incorrectly report the socket as being dead. I have not worked with request id's in the MPV JSON-IPC myself, so I'm not certain what the lib is doing here, but I remember seeing them mentioned in the MPV docs. I will attempt to hack at it a bit to see if I can figure it out and maybe offer a solution but I wanted to report it so that you're aware.

Running the new Debian Bookworm (Raspberry Pi OS on a Raspi 5) with a repo-installed version of MPV.

**Comment by utdream** [comment]
I updated the event_callback() method to the following so I could see what call was causing the error:

```python
    def event_callback(self, data):
        """Internal callback for recieving events from MPV."""
        log.debug("Received IPC socket data: {0}".format(data))
        if "request_id" in data:
            self.cid_result[data["request_id"]] = data
            self.cid_wait[data["request_id"]].set()
        elif "event" in data:
            self.callback(data["event"], data)
``` 

and I got the following in the logs:

```
[DEBU 2024-03-26 09:18:43,793 python_mpv_jsonipc:313] Received IPC socket data: {'data': False, 'request_id': 936, 'error': 'success'}
[DEBU 2024-03-26 09:18:43,893 python_mpv_jsonipc:313] Received IPC socket data: {'data': False, 'request_id': 937, 'error': 'success'}
[DEBU 2024-03-26 09:18:43,893 python_mpv_jsonipc:313] Received IPC socket data: {'data': False, 'request_id': 938, 'error': 'success'}
[DEBU 2024-03-26 09:18:43,894 python_mpv_jsonipc:313] Received IPC socket data: {'data': False, 'request_id': 939, 'error': 'success'}
[DEBU 2024-03-26 09:18:43,994 python_mpv_jsonipc:313] Received IPC socket data: {'data': False, 'request_id': 940, 'error': 'success'}
[DEBU 2024-03-26 09:18:43,995 python_mpv_jsonipc:313] Received IPC socket data: {'data': False, 'request_id': 941, 'error': 'success'}
[DEBU 2024-03-26 09:18:43,995 python_mpv_jsonipc:313] Received IPC socket data: {'data': False, 'request_id': 942, 'error': 'success'}
[DEBU 2024-03-26 09:18:44,096 python_mpv_jsonipc:313] Received IPC socket data: {'data': False, 'request_id': 943, 'error': 'success'}
[DEBU 2024-03-26 09:18:44,096 python_mpv_jsonipc:313] Received IPC socket data: {'data': False, 'request_id': 944, 'error': 'success'}
[DEBU 2024-03-26 09:18:44,096 python_mpv_jsonipc:313] Received IPC socket data: {'data': False, 'request_id': 945, 'error': 'success'}
[DEBU 2024-03-26 09:18:44,157 python_mpv_jsonipc:313] Received IPC socket data: {'data': {'playlist_entry_id': 3}, 'request_id': 7, 'error': 'success'}
[ERRO 2024-03-26 09:18:44,158 python_mpv_jsonipc:192] Socket connection died.
Traceback (most recent call last):
  File "/opt/npctv/api/lib/python_mpv_jsonipc.py", line 189, in run
    self.callback(json_data)
  File "/opt/npctv/api/lib/python_mpv_jsonipc.py", line 316, in event_callback
    self.cid_wait[data["request_id"]].set()
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 7
``` 

My app is what is doing all the status update calls before the error. I'm monitoring the stream to make sure it stays healthy, and to let the watcher know when the stream is buffering and what-not. This error occurs when I change the stream that MPV is playing. The "KeyError" is always 7, so it seems the lib is not handling this request_id properly?

I'll keep hacking at it and see if I can help find a fix.

**Comment by utdream** [comment]
Added a line that also showed the command that was sent along with the command_id.
```
[DEBU 2024-03-26 13:47:35,080 python_mpv_jsonipc:347] Sending IPC socket command: {'command': ['loadfile', 'udp://230.0.0.1:8002?overrun_nonfatal=1'], 'request_id': 7}
[DEBU 2024-03-26 13:47:35,080 python_mpv_jsonipc:313] Received IPC socket data: {'data': {'playlist_entry_id': 3}, 'request_id': 7, 'error': 'success'}
```
This looks okay to me. I have no idea why this is failing.

Adding a protective get() line before the set() prevents the library from crashing, but the calling thread will never get a response and times out.

```python
    def event_callback(self, data):
        """Internal callback for recieving events from MPV."""
        log.debug("Received IPC socket data: {0}".format(data))
        if "request_id" in data:
            self.cid_result[data["request_id"]] = data
            if self.cid_wait.get(data["request_id"]):
                self.cid_wait[data["request_id"]].set()
        elif "event" in data:
            self.callback(data["event"], data)
``` 

The only thing I can figure is that some time between the time that self.cid_wait was set and the event_callback() method it was removed or reset... but I have not found where yet...

**Comment by utdream** [comment]
I believe I have figured this out. I believe the issue is due to the kind of threads the API was using vs the kind of threads my main app was using. Appreciate you allowing me to think out load in your issues area.

If you create separate objects - one for the app and others for each API worker - you can get things working just fine.

If this has been emailing someone and bothering them, please accept my apologies and gratitude for making this library available.
